let dados = [
  {
  titulo: "O Doutor",
  titulo2: "O Senhor do Tempo",
  descricao: "Um Senhor do Tempo de Gallifrey que viaja pelo tempo e espaço em sua TARDIS, ajudando pessoas e defendendo o universo de ameaças.",
  link: "https://doctorwho.fandom.com/pt/wiki/O_Doutor",
  planeta: "Gallifrey",
  tags: ["tempo", "Doutor", "companheiro", "alien", "universo", "aventura", "moral", "responsabilidade", "paradoxo", "TARDIS", "Sonicscrew", "Daleks", "Cybermen", "Master", "Weeping Angels", "Sontarans"],
  img: "galeria_aliens/Doctor10.jpg",
  audio: "../audios/Voz_do_Doutor.mp3"
}, 
{
  titulo : "Daleks",
  titulo2 : "Daleks",
  descricao : "Os Daleks são uma das raças alienígenas mais temidas do universo de Doctor Who. Criados por Davros em Skaro, são mutantes xenófobos confinados em máquinas de guerra. Sua principal característica é a obsessão pela exterminação de outras formas de vida e a busca pela dominação universal. Com um design icônico e uma voz imponente, os Daleks se tornaram um dos inimigos mais clássicos e memoráveis da série.",
  link : "https://doctorwho.fandom.com/pt/wiki/Dalek",
  planeta : "Skaro",
  tags: ["extermínio", "perfeição", "superioridade", "ódio", "ciência", "Skaro", "caixa", "voz", "raio de morte", "Doutor", "fascínio", "guerra", "ciência ficção", "invasão", "Doctor Who"],
  img : "galeria_aliens/Daleks.jpg",
  audio: "../audios/Exterminar.mp3",
},
  {
    titulo: "Anjos Lamentadores",
    titulo2: "Anjos Lamentadores",
    descricao: "Os Anjos Lamentadores são estátuas de anjos que se movem quando não estão sendo observados. Eles se alimentam da energia vital de suas vítimas, enviando-as de volta no tempo.",
    link: "https://tardis.fandom.com/wiki/Weeping_Angel",
    planeta: "Desconhecido",
    tags: ["tempo", "percepção", "estático", "terror", "imortal", "asas", "visão", "维塔", "sobrenatural", "horror", "mistério", "Doctor Who"],
    img : "galeria_aliens/AnjosLamentadores.jpeg",
    audio: "../audios/NaoPisca.mp3",
  },
  {
    titulo: "Cybermen",
    titulo2: "Cybermen",
    descricao: "Os Cybermen são seres humanos modificados com partes mecânicas, buscando a perfeição através da tecnologia e da eliminação da fraqueza humana.",
    link: "https://doctorwho.fandom.com/pt/wiki/Cyberman",
    planeta: "Mondas",
    tags: ["cibernético", "perfeição", "conversão", "imortalidade", "coletivo", "Mondas", "cérebro", "upgrades", "Inimigo do Doutor", "frio", "sem emoção", "guerra", "ciência", "Doctor Who"],
    img: "galeria_aliens/Cyberman.jpeg",
    audio: "../audios/Cybermanvoz.mp3",
  },
  {
    titulo: "Oods",
    titulo2: "Oods",
    descricao: "Os Ood são seres pacíficos e telepáticos, servindo como mensageiros e guias. Eles são conectados a uma mente coletiva e possuem uma profunda conexão com o universo.",
    link: "https://tardis.fandom.com/wiki/Ood",
    planeta: "Ood-Sphere",
    tags: ["pacífico", "explorador", "religioso", "telepático", "submissão", "cabeça", "Planeta Ood", "Ood Sigma", "abelhas", "extraterrestre", "espiritual", "comunidade", "misterioso", "Doctor Who"],
    img: "galeria_aliens/Oods.jpg",
    audio: "../audios/Vale_Decem.mp3",
  },
  {
    titulo: "O Silêncio",
    titulo2: "O Silêncio",
    descricao: "Os Silêncio são uma raça alienígena que se infiltrou na sociedade humana, controlando as mentes das pessoas através de um simples toque. Eles são extremamente perigosos e manipuladores.",
    link: "https://tardis.fandom.com/wiki/The_Silence",
    planeta: "Desconhecido",
    tags: ["Silêncio", "medo", "controle mental", "conspiração", "história", "Padroeiros", "Clara Oswald", "Ángelos Chorosos", "Ponto Fixo", "Guerra dos Tempo", "misterioso", "terror", "revelação", "sobrevivência", "Doctor Who"],
    img: "galeria_aliens/Silents.jpg",
    audio: "",
  },
  {
    titulo: "Sontarans",
    titulo2: "Sontarans",
    descricao: "Os Sontarans são guerreiros clonados, obcecados por guerra e conquista. São seres racionais e estratégicos, mas também extremamente violentos.",
    link: "https://tardis.fandom.com/wiki/Sontaran",
    planeta: "Sontar",
    tags: ["guerreiros", "clones", "guerra", "conquista", "racionais", "violentos", "Sontar", "Doctor Who"],
    img: "galeria_aliens/Sontarans.jpg",
    audio: "",
  }
]

